name = "gitconfig"
description = "My gitconfig file"

[vars]
user.name = "First Last"
# Rather than specifying vars in the patina file, an external vars file can be specified
# user.email = "user@domain.com"

[[files]]
template = "gitconfig.hbs"
target = "output/.gitconfig"
