name = "no-templating"
description = "This patina demonstrates a file that has templating disabled."

[[files]]
template = "templates/no-templating.txt"
target = "../../output/hello.txt"
disable_templating = true
