name = "gitconfig"
description = "My gitconfig file"

[vars]
user.email = "user@domain.com"
user.name = "First Last"

[[files]]
template = "examples/gitconfig/gitconfig.hbs"
target = "output/.gitconfig"
