name = "gitconfig"
description = "My gitconfig file"

[vars]
user.email = "user@domain.com"
user.name = "First Last"

[[files]]
template = "gitconfig.hbs"
target = "../../output/.gitconfig"

[[files]]
template = "lazygit.config.yml"
target = "../../output/lazygit.config"
