name = "multiple files"
description = "This is a patina with multiple files"

[vars]
a = "A"
b = "B"

[[files]]
template = "file-a.txt.hbs"
target = "../../output/file-a.txt"

[[files]]
template = "file-b.txt.hbs"
target = "../../output/file-b.txt"
