name: 🏷️ Check Version

on:
  # TODO: remove the branch trigger before merge
  push:
    branches:
      - axis7818/versioning
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check Cargo version
        run: scripts/check_version.sh
