name: 🏷️ Check Version

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if src files changed
        id: changed_files
        run: echo "::set-output name=files_changed::$(git diff --name-only main ${{ github.sha }} | grep -q '^src/' && echo true || echo false)"

      - name: Check Cargo version
        if: ${{ steps.changed_files.outputs.files_changed == 'true' }}
        run: scripts/check_version.sh
