name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: cargo build

      - name: Run tests
        run: cargo test

      - name: Run formatter
        run: cargo fmt -- --check

      - name: Run linter
        run: cargo clippy -- -D warnings

      - name: Check Cargo version
        if: github.ref != 'refs/heads/main'
        run: |
          PREV_VERSION=$(git show main:Cargo.toml | grep '^version' | awk '{print $3}')
          CURR_VERSION=$(grep '^version' Cargo.toml | awk '{print $3}')
          if [ "$PREV_VERSION" = "$CURR_VERSION" ]; then
            echo "Cargo version has not incremented."
            exit 1
          else
            echo "Cargo version has incremented."
          fi
